name: build linux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download media files
      # Download necessary files according to readme.md
      run: |
        mkdir baseq2
        wget -O baseq2/q2rtx_media.pkz https://github.com/NVIDIA/Q2RTX/releases/download/v1.3.0/q2rtx_media.pkz
        wget -O baseq2/shader_balls.pkz https://github.com/NVIDIA/Q2RTX/releases/download/v1.2.0/shader_balls.pkz
        wget -O baseq2/blue_noise.pkz https://github.com/NVIDIA/Q2RTX/releases/download/v1.0.0/blue_noise.pkz

    - name: Install dependencies
      # Install missing dependencies necessary to build project
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc glslang-tools g++ libgl-dev libopenal-dev libvulkan-dev libxext-dev zlib1g-dev

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          baseq2/
          q2rtx
          q2rtxded
